In [1]:
import numpy as np

# 初始出链数量占比
a = np.array([[0, 1/2, 1, 0], 
			[1/3, 0, 0, 1/2],
			[1/3, 0, 0, 1/2],
			[1/3, 1/2, 0, 0]])
a_leak = np.array([[0, 0, 0, 1/2], 
				   [0, 0, 0, 1/2],
				   [0, 1, 0, 0],
				   [0, 0, 1, 0]])

a_sink = np.array([[0, 0, 0, 0], 
				   [1/2, 0, 0, 1],
				   [0, 1, 1, 0],
				   [1/2, 0, 0, 0]])

# 假设每个的权重一样
b = np.array([1/4, 1/4, 1/4, 1/4])
w = b

def work(a, w):
	for i in range(100):
		w = np.dot(a, w)
		print(w)

def random_work(a, w, n):
	d = 0.85
	for i in range(100):
		w = (1-d)/n + d*np.dot(a, w)
		print(w)

#work(a, w)
random_work(a, w, 4)
#random_work(a_leak, w, 4)
#random_work(a_sink, w, 4)

[0.35625    0.21458333 0.21458333 0.21458333]
[0.31109375 0.22963542 0.22963542 0.22963542]
[0.33028516 0.22323828 0.22323828 0.22323828]
[0.32212881 0.22595706 0.22595706 0.22595706]
[0.32559526 0.22480158 0.22480158 0.22480158]
[0.32412202 0.22529266 0.22529266 0.22529266]
[0.32474814 0.22508395 0.22508395 0.22508395]
[0.32448204 0.22517265 0.22517265 0.22517265]
[0.32459513 0.22513496 0.22513496 0.22513496]
[0.32454707 0.22515098 0.22515098 0.22515098]
[0.3245675  0.22514417 0.22514417 0.22514417]
[0.32455881 0.22514706 0.22514706 0.22514706]
[0.3245625  0.22514583 0.22514583 0.22514583]
[0.32456094 0.22514635 0.22514635 0.22514635]
[0.3245616  0.22514613 0.22514613 0.22514613]
[0.32456132 0.22514623 0.22514623 0.22514623]
[0.32456144 0.22514619 0.22514619 0.22514619]
[0.32456139 0.2251462  0.2251462  0.2251462 ]
[0.32456141 0.2251462  0.2251462  0.2251462 ]
[0.3245614 0.2251462 0.2251462 0.2251462]
[0.3245614 0.2251462 0.2251462 0.2251462]
[0.3245614 0.2251462 0.2251462 0.2251462]
