In [2]:
import numpy as np

In [17]:
# 初始出链数量占比
a = np.array([[0, 0, 0, 1/3, 0, 0], 
			[1/4, 0, 0, 0, 1/2, 0],
			[0, 1, 0, 1/3, 1/2, 0],
            [1/4, 0, 0, 0, 0, 1], 
            [1/4, 0, 1, 1/3, 0, 0], 
			[1/4, 0, 0, 0, 0, 0]])


# 随机权重
b = np.array([1, 0, 0, 0, 0, 0])
w = b

def work(a, w):
    
    for i in range(100):
        w = np.dot(a, w)
        print(w)


def random_work(a, w, n):
    d = 0.85
    for i in range(100):
        w = (1-d)/n + d*np.dot(a, w)
        print(w)
print("简化模型 results: ", work(a,w))
work(a, w)
print("======================")
random_work(a, w, 6)


[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.25 0.   0.25 0.25 0.25]
[0.   0.